In [10]:
# import pandas
import pandas as pd 

df = pd.read_csv(r'C:\Users\suyas\Downloads\BostonHousing.csv')


print(df.head())

      CRIM    ZN  INDUS  CHAS    NOX  ...  TAX  PTRATIO  LSTAT  MEDV  CAT. MEDV
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3   4.98  24.0          0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8   9.14  21.6          0
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8   4.03  34.7          1
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7   2.94  33.4          1
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7   5.33  36.2          1

[5 rows x 14 columns]

In [9]:
# import csv file 
ddf = pd.read_csv(r'C:\Users\suyas\Downloads\diabetes.csv')
ddf.head()

   Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [ ]:
# import from excel
#pd.read_excel(_)

In [15]:
# export datasets into csv 
df.to_csv(r'C:\Users\suyas\Downloads\BostonHsing.csv')

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   CRIM       506 non-null    float64
 1   ZN         506 non-null    float64
 2   INDUS      506 non-null    float64
 3   CHAS       506 non-null    int64
 4   NOX        506 non-null    float64
 5   RM         506 non-null    float64
 6   AGE        506 non-null    float64
 7   DIS        506 non-null    float64
 8   RAD        506 non-null    int64
 9   TAX        506 non-null    int64
 10  PTRATIO    506 non-null    float64
 11  LSTAT      506 non-null    float64
 12  MEDV       506 non-null    float64
 13  CAT. MEDV  506 non-null    int64
dtypes: float64(10), int64(4)
memory usage: 55.5 KB

In [25]:
#find the missing value in each coloumn
df.isnull() #we do not hasve any missing values
df.isnull().sum()

CRIM         0
ZN           0
INDUS        0
CHAS         0
NOX          0
RM           0
AGE          0
DIS          0
RAD          0
TAX          0
PTRATIO      0
LSTAT        0
MEDV         0
CAT. MEDV    0
dtype: int64

In [31]:
# counting the values by lable
ddf.value_counts('Outcome')

Outcome
0    500
1    268
Name: count, dtype: int64

In [32]:
ddf.value_counts('Age')

Age
22    72
21    63
25    48
24    46
23    38
28    35
26    33
27    32
29    29
31    24
41    22
30    21
37    19
42    18
33    17
32    16
38    16
36    16
45    15
34    14
43    13
46    13
40    13
39    12
35    10
50     8
51     8
44     8
52     8
58     7
54     6
47     6
53     5
57     5
60     5
48     5
49     5
62     4
55     4
66     4
63     4
59     3
56     3
65     3
67     3
61     2
69     2
72     1
81     1
64     1
70     1
68     1
Name: count, dtype: int64

In [33]:
# calculating mean in the data 
ddf.groupby('Outcome').mean()

         Pregnancies     Glucose  ...  DiabetesPedigreeFunction        Age
Outcome                           ...
0           3.298000  109.980000  ...                  0.429734  31.190000
1           4.865672  141.257463  ...                  0.550500  37.067164

[2 rows x 8 columns]

In [34]:
#counting 
ddf.count()

Pregnancies                 768
Glucose                     768
BloodPressure               768
SkinThickness               768
Insulin                     768
BMI                         768
DiabetesPedigreeFunction    768
Age                         768
Outcome                     768
dtype: int64

In [35]:
#mean value coloumn wise
ddf.mean()

Pregnancies                   3.845052
Glucose                     120.894531
BloodPressure                69.105469
SkinThickness                20.536458
Insulin                      79.799479
BMI                          31.992578
DiabetesPedigreeFunction      0.471876
Age                          33.240885
Outcome                       0.348958
dtype: float64

In [36]:
#standard daviation
ddf.std()

Pregnancies                   3.369578
Glucose                      31.972618
BloodPressure                19.355807
SkinThickness                15.952218
Insulin                     115.244002
BMI                           7.884160
DiabetesPedigreeFunction      0.331329
Age                          11.760232
Outcome                       0.476951
dtype: float64

In [37]:
# min and max val
print(df.min())
print(df.max())

CRIM           0.00632
ZN             0.00000
INDUS          0.46000
CHAS           0.00000
NOX            0.38500
RM             3.56100
AGE            2.90000
DIS            1.12960
RAD            1.00000
TAX          187.00000
PTRATIO       12.60000
LSTAT          1.73000
MEDV           5.00000
CAT. MEDV      0.00000
dtype: float64
CRIM          88.9762
ZN           100.0000
INDUS         27.7400
CHAS           1.0000
NOX            0.8710
RM             8.7800
AGE          100.0000
DIS           12.1265
RAD           24.0000
TAX          711.0000
PTRATIO       22.0000
LSTAT         37.9700
MEDV          50.0000
CAT. MEDV      1.0000
dtype: float64

In [38]:
# all statistical values 
ddf.describe()

       Pregnancies     Glucose  ...         Age     Outcome
count   768.000000  768.000000  ...  768.000000  768.000000
mean      3.845052  120.894531  ...   33.240885    0.348958
std       3.369578   31.972618  ...   11.760232    0.476951
min       0.000000    0.000000  ...   21.000000    0.000000
25%       1.000000   99.000000  ...   24.000000    0.000000
50%       3.000000  117.000000  ...   29.000000    0.000000
75%       6.000000  140.250000  ...   41.000000    1.000000
max      17.000000  199.000000  ...   81.000000    1.000000

[8 rows x 9 columns]

In [ ]:
# manipulating data 
#adding coloumn
df = df

ValueError: Cannot set a DataFrame with multiple columns to the single column price

In [55]:
# drop the row
drop1=df.drop(index=0,axis=0)
print(drop1)

        CRIM   ZN  INDUS  CHAS    NOX  ...  TAX  PTRATIO  LSTAT  MEDV  CAT. MEDV
1    0.02731  0.0   7.07     0  0.469  ...  242     17.8   9.14  21.6          0
2    0.02729  0.0   7.07     0  0.469  ...  242     17.8   4.03  34.7          1
3    0.03237  0.0   2.18     0  0.458  ...  222     18.7   2.94  33.4          1
4    0.06905  0.0   2.18     0  0.458  ...  222     18.7   5.33  36.2          1
5    0.02985  0.0   2.18     0  0.458  ...  222     18.7   5.21  28.7          0
..       ...  ...    ...   ...    ...  ...  ...      ...    ...   ...        ...
501  0.06263  0.0  11.93     0  0.573  ...  273     21.0   9.67  22.4          0
502  0.04527  0.0  11.93     0  0.573  ...  273     21.0   9.08  20.6          0
503  0.06076  0.0  11.93     0  0.573  ...  273     21.0   5.64  23.9          0
504  0.10959  0.0  11.93     0  0.573  ...  273     21.0   6.48  22.0          0
505  0.04741  0.0  11.93     0  0.573  ...  273     21.0   7.88  11.9          0

[505 rows x 14 columns]

In [56]:
# drop the coloumn
drop2=df.drop(columns='INDUS',axis=2)
print(drop2)

        CRIM    ZN  CHAS    NOX     RM  ...  TAX  PTRATIO  LSTAT  MEDV  CAT. MEDV
0    0.00632  18.0     0  0.538  6.575  ...  296     15.3   4.98  24.0          0
1    0.02731   0.0     0  0.469  6.421  ...  242     17.8   9.14  21.6          0
2    0.02729   0.0     0  0.469  7.185  ...  242     17.8   4.03  34.7          1
3    0.03237   0.0     0  0.458  6.998  ...  222     18.7   2.94  33.4          1
4    0.06905   0.0     0  0.458  7.147  ...  222     18.7   5.33  36.2          1
..       ...   ...   ...    ...    ...  ...  ...      ...    ...   ...        ...
501  0.06263   0.0     0  0.573  6.593  ...  273     21.0   9.67  22.4          0
502  0.04527   0.0     0  0.573  6.120  ...  273     21.0   9.08  20.6          0
503  0.06076   0.0     0  0.573  6.976  ...  273     21.0   5.64  23.9          0
504  0.10959   0.0     0  0.573  6.794  ...  273     21.0   6.48  22.0          0
505  0.04741   0.0     0  0.573  6.030  ...  273     21.0   7.88  11.9          0

[506 rows x 13 columns]

In [49]:
# locate a row
df.iloc[4]

CRIM           0.06905
ZN             0.00000
INDUS          2.18000
CHAS           0.00000
NOX            0.45800
RM             7.14700
AGE           54.20000
DIS            6.06220
RAD            3.00000
TAX          222.00000
PTRATIO       18.70000
LSTAT          5.33000
MEDV          36.20000
CAT. MEDV      1.00000
Name: 4, dtype: float64

In [50]:
#locate a column
print(df.iloc[:,0])
print(df.iloc[:,1])
print(df.iloc[:,2])
print(df.iloc[:,-1])

0      0.00632
1      0.02731
2      0.02729
3      0.03237
4      0.06905
        ...
501    0.06263
502    0.04527
503    0.06076
504    0.10959
505    0.04741
Name: CRIM, Length: 506, dtype: float64
0      18.0
1       0.0
2       0.0
3       0.0
4       0.0
       ...
501     0.0
502     0.0
503     0.0
504     0.0
505     0.0
Name: ZN, Length: 506, dtype: float64
0       2.31
1       7.07
2       7.07
3       2.18
4       2.18
       ...
501    11.93
502    11.93
503    11.93
504    11.93
505    11.93
Name: INDUS, Length: 506, dtype: float64
0      0
1      0
2      1
3      1
4      1
      ..
501    0
502    0
503    0
504    0
505    0
Name: CAT. MEDV, Length: 506, dtype: int64